version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8090
    volumes:
      - .:/app
    ports:
      - "8090:8090"
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql